# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Scan code with HLint
description: Scan Haskell code for possible improvements using HLint.

inputs:
  binary:
    description: Path to the hlint binary.
    required: false
  path:
    description: Path of file or directory that HLint will be told to scan.
    required: false
    default: .
  hints:
    description: Path for HLint configuration file.
    required: false
  category:
    description: String used by GitHub code scanning for matching the analyses.
    required: false
  token:
    description: Access token to fetch the repository and write the code scanning results from HLint to GitHub code scanning.
    required: false
    default: ${{ github.token }}
  fail-on:
    description: |
      If not empty, then this disables code scanning and instead outputs annotations.
      The value can be one of 'never', 'error', 'warning', or 'note', which denotes at what level a non-zero exit can happen.
      This is only intended for use in private GitHub repositories which do not have code scanning available.
    required: false

outputs:
  sarif-id:
    description: The ID of the uploaded SARIF file.
    value: ${{ steps.upload-sarif.outputs.sarif-id }}

runs:
  using: docker
  image: docker://ghcr.io/haskell-actions/hlint-scan:v1.2.0
  args:
    - binary=${{ inputs.binary }}
    - path=${{ inputs.path }}
    - category=${{ inputs.category }}
    - token=${{ inputs.token }}
    - fail-on=${{ inputs.fail-on }}

branding:
  icon: 'crosshair'
  color: 'purple'
