# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name:                hlint-scan
version:             1.2.0
github:              "haskell-actions/hlint-scan"
license:             Apache-2.0
author:              "Yoo Chung"
maintainer:          "chungyc@google.com"
copyright:           "Copyright 2023 Google LLC"

extra-source-files:
- action.yaml
- Dockerfile
- LICENSE
- README.md
- docs/**

synopsis:            Code scanning GitHub action using HLint.
category:            GitHub, Development

description: |
  Scans code with HLint and uploads its analysis results to GitHub code scanning.
  This is intended to be used as a standalone application on GitHub and not a library.
  See <https://github.com/haskell-actions/hlint-scan>.

dependencies:
- base

language: GHC2021

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Werror
- -O2

library:
  source-dirs: src
  dependencies:
  - aeson
  - base64
  - bytestring
  - containers
  - filepath
  - github-rest
  - process
  - text
  - vector
  - zlib

executables:
  hlint-scan:
    main:                Main.hs
    source-dirs:         app

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - hlint-scan

    # Work around https://github.com/sol/hpack/issues/303.
    when:
      condition: false
      other-modules: Paths_hlint_scan

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - hlint-scan
    - hspec
    - QuickCheck
    - aeson
    - base64
    - bytestring
    - github-rest
    - quickcheck-instances
    - text
    - vector
    - zlib

    # Work around https://github.com/sol/hpack/issues/303.
    when:
      condition: false
      other-modules:
      - Paths_hlint_scan
