name: HLint
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '5 4 14 * *'

jobs:
  hlint:
    name: Scan code with HLint
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results.
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: haskell-actions/hlint-scan@abd8bbb55afd1ec2c86bc28e081c1ca49037dd9c # v1.3.0
